apiVersion: apps/v1
kind: Deployment
metadata:
  name: aserw
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aserw
  template:
    metadata:
      labels:
        app: 
    spec:aserw
      containers:
      - image: okteto.dev/ray:latest
        name: aserw
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "3aee68d8-c36d-4b0e-865f-80d96bcb99e8"
        - name: Vless_Path
          value: "/vlty434"
        - name: Vmess_UUID
          value: "3aee68d8-c36d-4b0e-865f-80d96bcb99e8"
        - name: Vmess_Path
          value: "/vm6iuj66"
        - name: Share_Path
          value: "/v2link"
